{{- if or .Values.backend.httpRoute.enabled .Values.frontend.httpRoute.enabled -}}
{{- $fullName := include "ConfiaPe.Loans.CD.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ConfiaPe.Loans.CD.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- if .Values.backend.httpRoute.enabled }}
    {{- range .Values.backend.httpRoute.rules }}
    - matches:
      {{- range .matches }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value }}
          {{- if .headers }}
          headers:
            {{- toYaml .headers | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $fullName }}-backend
          port: {{ $.Values.backend.service.port }}
          weight: 1
    {{- end }}
  {{- end }}
  {{- if .Values.frontend.httpRoute.enabled }}
    {{- range .Values.frontend.httpRoute.rules }}
    - matches:
      {{- range .matches }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value }}
          {{- if .headers }}
          headers:
            {{- toYaml .headers | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $fullName }}-frontend
          port: {{ $.Values.frontend.service.port }}
          weight: 1
    {{- end }}
  {{- end }}
{{- end }}
